name: pyrecon_dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools
  - psycopg2
  - conda-build
  - lxml
  - scikit-image
  - pip:
    - -r ./pip-requirements.txt
    - git+https://github.com/funkelab/funlib.show.neuroglancer
